export const GAME_CONFIG = {
  TOP_BAR_HEIGHT: 50,
  LETTERS_DOWN_INTERVAL: 30,
  GOLDEN_LETTERS_DOWN_INTERVAL: 40,
  LETTERS_DOWN_INTERVAL_MS: 100,
  GAME_SESSION_SECOND: 20,
  LETTER_ADD_INTERVAL_MS: 400,
  LIFE_COUNT: 5,
};
